# Generated by Django 5.2.18 on 2026-10-08 09:08

import core.crypto
import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
                ("description", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="StageDefinition",
            fields=[
                (
                    "code",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ASSET", "Per location / asset"),
                            ("FARMER", "Per farmer (derived)"),
                        ],
                        default="ASSET",
                        max_length=10,
                    ),
                ),
                (
                    "asset_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Empty = applies to all asset types",
                    ),
                ),
                (
                    "edit_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Roles allowed to update; empty = default",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Company Administrator"),
                            ("PROJECT_MANAGER", "Project Manager"),
                            ("ROW_OFFICER", "Land / ROW Officer"),
                            ("SURVEYOR", "Field Surveyor"),
                            ("FINANCE", "Finance User"),
                            ("MANAGEMENT", "Management"),
                            ("FARMER", "Farmer User"),
                        ],
                        default="SURVEYOR",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reported GPS accuracy in metres",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("gps_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("POLE", "Pole"),
                            ("TOWER", "Tower"),
                            ("SUBSTATION", "Substation"),
                            ("ACCESS_ROAD", "Access Road"),
                            ("LINE", "Line"),
                            ("OTHER", "Other"),
                        ],
                        default="POLE",
                        max_length=20,
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(
                        max_length=60, verbose_name="Pole / Tower / Asset No."
                    ),
                ),
                (
                    "line_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Line / Corridor"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gps_captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["project", "asset_number"],
            },
        ),
        migrations.CreateModel(
            name="AssetMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reported GPS accuracy in metres",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("gps_captured_at", models.DateTimeField(blank=True, null=True)),
                ("stage_code", models.CharField(max_length=30)),
                ("completed", models.BooleanField(default=False)),
                ("completed_on", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("AUTO", "Automatic")],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="core.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("APPROVE", "Approve"),
                            ("VIEW_SENSITIVE", "Viewed sensitive document"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("LOGIN", "Login"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=60)),
                ("object_repr", models.CharField(blank=True, max_length=300)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="WEB", max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("village", models.CharField(blank=True, max_length=120)),
                ("hobli", models.CharField(blank=True, max_length=120)),
                ("taluk", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                (
                    "state",
                    models.CharField(blank=True, default="Karnataka", max_length=120),
                ),
                (
                    "farmer_code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Farmer ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Farmer name")),
                (
                    "relation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S/O", "Son of"),
                            ("D/O", "Daughter of"),
                            ("W/O", "Wife of"),
                            ("H/O", "Husband of"),
                            ("C/O", "Care of"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "relation_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Father / Husband name"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\- ]{6,15}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "alt_mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\- ]{6,15}$", "Enter a valid phone number"
                            )
                        ],
                        verbose_name="Alternate mobile",
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("JOINT_OWNER", "Joint owner"),
                            ("CLAIMANT", "Claimant"),
                            ("DECEASED", "Deceased (legal heirs)"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "aadhaar_last4",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{4}$", "Enter only the last 4 digits of Aadhaar"
                            )
                        ],
                        verbose_name="Aadhaar (last 4 digits)",
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("NOT_COLLECTED", "Not collected"),
                            ("COLLECTED", "Collected"),
                            ("VERIFIED", "Verified"),
                        ],
                        default="NOT_COLLECTED",
                        max_length=20,
                    ),
                ),
                ("kyc_collected_on", models.DateField(blank=True, null=True)),
                ("kyc_verified_on", models.DateField(blank=True, null=True)),
                ("bank_account_holder", models.CharField(blank=True, max_length=200)),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("bank_branch", models.CharField(blank=True, max_length=200)),
                ("bank_account_number", core.crypto.EncryptedTextField(blank=True)),
                (
                    "bank_ifsc",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]{4}0[A-Za-z0-9]{6}$",
                                "Enter a valid 11-character IFSC",
                            )
                        ],
                        verbose_name="IFSC",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kyc_collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kyc_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["farmer_code", "name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="farmer",
            field=models.OneToOneField(
                blank=True,
                help_text="For future Farmer User logins",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_account",
                to="core.farmer",
            ),
        ),
        migrations.CreateModel(
            name="LandOwnership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "is_primary_payee",
                    models.BooleanField(
                        default=False, verbose_name="Primary / representative payee"
                    ),
                ),
                (
                    "share_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reserved for future split compensation",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="core.farmer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandParcel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reported GPS accuracy in metres",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("gps_captured_at", models.DateTimeField(blank=True, null=True)),
                ("village", models.CharField(blank=True, max_length=120)),
                ("hobli", models.CharField(blank=True, max_length=120)),
                ("taluk", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                (
                    "state",
                    models.CharField(blank=True, default="Karnataka", max_length=120),
                ),
                ("survey_number", models.CharField(max_length=40)),
                (
                    "hissa",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Sub-division / Hissa"
                    ),
                ),
                (
                    "extent_acres",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "extent_guntas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("JOINT", "Joint"),
                            ("GOVERNMENT", "Government"),
                            ("LEASED", "Leased / Tenant"),
                            ("OTHER", "Other"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("DRY", "Dry land"),
                            ("WET", "Wet / Irrigated"),
                            ("GARDEN", "Garden / Plantation"),
                            ("NON_AGRI", "Non-agricultural (NA)"),
                            ("GOVERNMENT", "Government land"),
                            ("OTHER", "Other"),
                        ],
                        default="DRY",
                        max_length=20,
                    ),
                ),
                (
                    "rtc_reference",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="RTC / Pahani reference",
                    ),
                ),
                ("mutation_details", models.TextField(blank=True)),
                (
                    "boundary_geojson",
                    models.JSONField(
                        blank=True,
                        help_text="Polygon boundary as GeoJSON geometry",
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="land_parcels",
                        through="core.LandOwnership",
                        to="core.farmer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["village", "survey_number", "hissa"],
            },
        ),
        migrations.AddField(
            model_name="landownership",
            name="land",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="core.landparcel",
            ),
        ),
        migrations.CreateModel(
            name="CropAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reported GPS accuracy in metres",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("gps_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KHARIF", "Kharif"),
                            ("RABI", "Rabi"),
                            ("SUMMER", "Summer / Zaid"),
                            ("PERENNIAL", "Perennial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("crop_type", models.CharField(max_length=100)),
                (
                    "crop_area_acres",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Crop area (acres)",
                    ),
                ),
                (
                    "crop_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOWN", "Sown / Germination"),
                            ("VEGETATIVE", "Vegetative"),
                            ("FLOWERING", "Flowering"),
                            ("MATURE", "Mature / Ready to harvest"),
                            ("HARVESTED", "Harvested"),
                            ("STANDING", "Standing (perennial)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assessment_date", models.DateField(blank=True, null=True)),
                ("field_inspection_notes", models.TextField(blank=True)),
                (
                    "revenue_assessment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Revenue dept. assessment (Rs)",
                    ),
                ),
                (
                    "company_assessment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Company assessment (Rs)",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crop_assessments",
                        to="core.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crop_assessments",
                        to="core.farmer",
                    ),
                ),
                (
                    "land_parcel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crop_assessments",
                        to="core.landparcel",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="Compensation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CROP", "Crop compensation"),
                            ("TREE", "Tree compensation"),
                            ("POLE_TOWER", "Pole / Tower compensation"),
                            ("LAND", "Land compensation"),
                            ("ACCESS_ROAD", "Access road compensation"),
                            ("OTHER", "Other compensation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="e.g. number of trees or area",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=30)),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPROVED", "Approved"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensations",
                        to="core.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensations",
                        to="core.cropassessment",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        help_text="Primary / representative payee",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compensations",
                        to="core.farmer",
                    ),
                ),
                (
                    "land_parcel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensations",
                        to="core.landparcel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="land_parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="core.landparcel",
            ),
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "agreement_number",
                    models.CharField(blank=True, max_length=40, unique=True),
                ),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("LEASE", "Lease"),
                            ("ROW", "Right of Way"),
                            ("EASEMENT", "Easement"),
                            ("CONSENT", "Consent"),
                            ("OTHER", "Other"),
                        ],
                        default="ROW",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("NEGOTIATION", "Under negotiation"),
                            ("EXECUTED", "Executed"),
                            ("REGISTERED", "Executed & registered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=300)),
                ("land_extent", models.CharField(blank=True, max_length=100)),
                ("agreement_date", models.DateField(blank=True, null=True)),
                (
                    "period_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Agreement period (months)"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("compensation_rate", models.CharField(blank=True, max_length=120)),
                (
                    "total_consideration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("registration_details", models.CharField(blank=True, max_length=300)),
                (
                    "stamp_duty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Stamp duty / charges",
                    ),
                ),
                ("witness_details", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True, related_name="agreements", to="core.asset"
                    ),
                ),
                (
                    "farmers",
                    models.ManyToManyField(
                        blank=True, related_name="agreements", to="core.farmer"
                    ),
                ),
                (
                    "land_parcel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agreements",
                        to="core.landparcel",
                    ),
                ),
            ],
            options={
                "ordering": ["-agreement_date", "agreement_number"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("IMPS", "IMPS"),
                            ("UPI", "UPI"),
                            ("CHEQUE", "Cheque"),
                            ("DD", "Demand draft"),
                            ("CASH", "Cash"),
                            ("OTHER", "Other"),
                        ],
                        default="NEFT",
                        max_length=10,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="UTR / Cheque / Reference No.",
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=60)),
                ("remarks", models.TextField(blank=True)),
                (
                    "compensation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.compensation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_received",
                        to="core.farmer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("village", models.CharField(blank=True, max_length=120)),
                ("hobli", models.CharField(blank=True, max_length=120)),
                ("taluk", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                (
                    "state",
                    models.CharField(blank=True, default="Karnataka", max_length=120),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "developer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Developer / Client"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("SOLAR", "Solar"),
                            ("WIND", "Wind"),
                            ("TRANSMISSION", "Transmission Line"),
                            ("DISTRIBUTION", "Distribution / Evacuation Line"),
                            ("SUBSTATION", "Substation"),
                            ("ROAD", "Access / Approach Road"),
                            ("OTHER", "Other"),
                        ],
                        default="TRANSMISSION",
                        max_length=20,
                    ),
                ),
                (
                    "voltage_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not applicable"),
                            ("11KV", "11 kV"),
                            ("33KV", "33 kV"),
                            ("66KV", "66 kV"),
                            ("110KV", "110 kV"),
                            ("220KV", "220 kV"),
                            ("400KV", "400 kV"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "corridor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Corridor / Route"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "route_geojson",
                    models.JSONField(
                        blank=True,
                        help_text="Corridor / route line(s) as GeoJSON geometry (e.g. from KML import)",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="landparcel",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="land_parcels", to="core.project"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="farmers", to="core.project"
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal degrees (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reported GPS accuracy in metres",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("gps_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("KYC_AADHAAR", "KYC - Aadhaar card"),
                            ("KYC_OTHER", "KYC - Other ID"),
                            ("BANK_PROOF", "Bank passbook / cheque"),
                            ("LAND_RTC", "RTC / Pahani"),
                            ("LAND_OTHER", "Other land document"),
                            ("AGREEMENT", "Signed agreement"),
                            ("SITE_PHOTO", "Site photo"),
                            ("CROP_PHOTO", "Crop photo"),
                            ("PAYMENT_RECEIPT", "Payment receipt"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "file",
                    models.FileField(
                        max_length=300, upload_to=core.models.document_upload_path
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("is_encrypted", models.BooleanField(default=False)),
                (
                    "captured_live",
                    models.BooleanField(
                        default=False,
                        help_text="Taken with the in-app camera (vs uploaded from gallery/files)",
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.agreement",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.asset",
                    ),
                ),
                (
                    "compensation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.compensation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.cropassessment",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.assetmilestone",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.farmer",
                    ),
                ),
                (
                    "land_parcel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.landparcel",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.payment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cropassessment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crop_assessments",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="compensation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compensations",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreements",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Projects this user is assigned to",
                related_name="assigned_users",
                to="core.project",
            ),
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                ("op_id", models.UUIDField(primary_key=True, serialize=False)),
                ("entity", models.CharField(max_length=40)),
                ("object_id", models.CharField(max_length=60)),
                ("ok", models.BooleanField(default=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="assetmilestone",
            constraint=models.UniqueConstraint(
                fields=("asset", "stage_code"), name="unique_asset_stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="landownership",
            constraint=models.UniqueConstraint(
                fields=("land", "farmer"), name="unique_land_farmer"
            ),
        ),
    ]
